title: Ayisha Yusibova
logo: "images/my_foto.png"
description: >
  Geoinformatics Specialist 
  <br><br>
  I am graduate with a master's degree in Geoinformatics and currently working as a GIS specialist. I am passionate about applying GIS tools to study the effects of climate change and environmental hazards in urban environments.  
  <br><br>
  I love making maps. Here, you can see my academic and personal projects that posted and I will be posting in the near future. 
   <br><br>
  <a href="https://www.linkedin.com/in/aisha-yusibova">LinkedIn</a> | <a href="https://www.linkedin.com/in/aisha-yusibova">Resume</a> 

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
