title: Ayisha Yusibova
logo: "images/my_foto.png"
description: >
  Geoinformatics Specialist 
  <br><br>
  I am a graduate with a master's degree in Geoinformatics, currently working as a GIS specialist. I am passionate about learning new GIS tools and creating projects.
  <br><br>
  Here, you can see my academic and personal projects that were posted, and I will keep updating.  
   <br><br>
  <a href="https://www.linkedin.com/in/aisha-yusibova">LinkedIn</a> | <a href="https://www.linkedin.com/in/aisha-yusibova">Resume</a> 

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: G-SR6FD64EL2
