title: Ayisha Yusibova
logo: "images/my_foto.png"
description: >
  Geoinformatics Specialist 
  <br><br>
  I am a GIS specialist passionate about applying GIS tools to study the effects of climate change and sustainable urban environments.  
  <br><br>
  <a href="https://www.linkedin.com/in/aisha-yusibova">LinkedIn</a> | <a href="https://www.linkedin.com/in/aisha-yusibova">Resume</a> 

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
